import { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const CATEGORIES: Category[] = [
  {
    id: 'all',
    name: 'All',
    description: 'Explore our complete range of high-performance fasteners.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-all')?.imageUrl || 'https://picsum.photos/seed/all/400/300',
  },
  {
    id: 'anchors',
    name: 'Anchors',
    description: 'Heavy duty anchoring systems for concrete and masonry.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-anchors')?.imageUrl || 'https://picsum.photos/seed/anchors/400/300',
  },
  {
    id: 'bits-sockets',
    name: 'Bits & Sockets',
    description: 'Industrial-grade driver bits, sockets, and accessories.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-bits-sockets')?.imageUrl || 'https://picsum.photos/seed/bits/400/300',
  },
  {
    id: 'bolts',
    name: 'Bolts',
    description: 'High-tensile hex bolts, carriage bolts, and specialized fasteners.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-bolts')?.imageUrl || 'https://picsum.photos/seed/bolts/400/300',
  },
  {
    id: 'new-screws',
    name: 'New Screws',
    description: 'The latest innovations in fastening technology and materials.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-new-screws')?.imageUrl || 'https://picsum.photos/seed/new/400/300',
  },
  {
    id: 'nuts',
    name: 'Nuts',
    description: 'Metric and imperial hex nuts, nyloc nuts, and wing nuts.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-nuts')?.imageUrl || 'https://picsum.photos/seed/nuts/400/300',
  },
  {
    id: 'rivets',
    name: 'Rivets',
    description: 'Complete range of blind rivets and installation tools.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-rivets')?.imageUrl || 'https://picsum.photos/seed/rivets/400/300',
  },
  {
    id: 'roofing-screws',
    name: 'Roofing Screws',
    description: 'Specialized fasteners for timber and steel roofing profiles.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-roofing-screws')?.imageUrl || 'https://picsum.photos/seed/roofing/400/300',
  },
  {
    id: 'screws',
    name: 'Screws',
    description: 'General purpose screws for wood, metal, and construction.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-screws')?.imageUrl || 'https://picsum.photos/seed/screws/400/300',
  },
  {
    id: 'self-drilling-screws',
    name: 'Self Drilling Screws',
    description: 'High-speed self-drilling fasteners for heavy metal applications.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-self-drilling-screws')?.imageUrl || 'https://picsum.photos/seed/self-drill/400/300',
  },
  {
    id: 'set-screws',
    name: 'Set Screws',
    description: 'Precision grubs and set screws for mechanical assemblies.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-set-screws')?.imageUrl || 'https://picsum.photos/seed/set/400/300',
  },
  {
    id: 'socket-head-fasteners',
    name: 'Socket Head Fasteners (Stainless Steel)',
    description: 'Marine-grade A2 and A4 stainless steel socket head screws.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-socket-head-fasteners')?.imageUrl || 'https://picsum.photos/seed/socket/400/300',
  },
  {
    id: 'threaded-rod',
    name: 'Threaded Rod',
    description: 'Continuous threaded rod in zinc and stainless steel finishes.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-threaded-rod')?.imageUrl || 'https://picsum.photos/seed/rod/400/300',
  },
  {
    id: 'wall-plugs',
    name: 'Wall Plugs',
    description: 'Professional grade nylon and universal wall plugs.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-wall-plugs')?.imageUrl || 'https://picsum.photos/seed/plugs/400/300',
  },
  {
    id: 'washers',
    name: 'Washers',
    description: 'Industrial flat, spring, and specialized washer varieties.',
    image: (PlaceHolderImages || []).find(img => img.id === 'cat-washers')?.imageUrl || 'https://picsum.photos/seed/washers/400/300',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'bolt-gutter',
    name: 'Gutter Bolts Only - Zinc Plated',
    description: 'Specialized gutter bolts with a mushroom head and slotted drive, zinc plated for corrosion resistance.',
    category: 'bolts',
    material: 'Steel',
    finish: 'Zinc Plated',
    headStyle: 'Mushroom Head',
    driveType: 'Slotted',
    price: 0.45,
    image: 'https://i.ibb.co/Ld3hS3tS/GUTTER-BOLTS-ONLY-ZINC-PLATED.jpg',
    stockStatus: 'In Stock',
    sizes: ['6 X 12', '6 X 16', '6 X 20', '6 X 25', '6 X 30', '6 X 40', '6 X 50', '6 X 60', '6 X 75', 'M6', 'M6 Square Pressed Nuts'],
    specs: { length: 'Multiple', diameter: 'M6', threadType: 'Metric' }
  },
  {
    id: 'bolt-hook',
    name: 'Hook Bolts',
    description: 'Industrial hook bolts for secure fastening and hanging applications.',
    category: 'bolts',
    material: 'Steel',
    finish: 'Zinc Plated',
    headStyle: 'Hook',
    driveType: 'Threaded',
    price: 1.15,
    image: 'https://i.ibb.co/cSr88w2p/Hook-Bolts.jpg',
    stockStatus: 'In Stock',
    specs: { length: 'N/A', diameter: 'N/A', threadType: 'Metric' }
  },
  {
    id: 'bit-1',
    name: 'Magnetic Socket / Nut Setter',
    description: 'Industrial grade magnetic nut setters for rapid fastening of hex head screws.',
    category: 'bits-sockets',
    material: 'Chrome Vanadium Steel',
    finish: 'Sandblasted',
    headStyle: 'Hex',
    driveType: '1/4" Hex Shank',
    price: 3.50,
    image: 'https://i.ibb.co/vvqWFYrG/MAGNETIC-SOCKET.jpg',
    stockStatus: 'In Stock',
    sizes: ['1/4 X 1/4 X 65 TEKS', '1/4 X 5/16 X 65 TEKS', '1/4 X 3/8 X 65 TOPSP', 'M10 X 65', '1/4X60 BIT HOLDER'],
    specs: { length: '65mm', diameter: 'Multiple', threadType: 'N/A' }
  },
  {
    id: 'bit-2',
    name: 'Phillips & Pozi Bits – Per Each',
    description: 'High-performance driver bits for heavy-duty industrial and construction use.',
    category: 'bits-sockets',
    material: 'S2 Tool Steel',
    finish: 'Titanium Coated',
    headStyle: 'Driver Bit',
    driveType: '1/4" Hex Shank',
    price: 0.75,
    image: 'https://i.ibb.co/Wvr8rjpN/PHILLIPS-POZI-BITS-1-PER-EACH.jpg',
    images: [
      'https://i.ibb.co/Wvr8rjpN/PHILLIPS-POZI-BITS-1-PER-EACH.jpg',
      'https://i.ibb.co/WWDXL8BG/PHILLIPS-POZI-BITS-2-PER-EACH.jpg'
    ],
    stockStatus: 'In Stock',
    variants: [
      {
        type: 'Phillips',
        options: ['#1 X 25', '#1 X 50', '#2 X 25', '#2 X 50', '#3 X 25', '#3 X 50']
      },
      {
        type: 'Pozi',
        options: ['#1 X 25', '#1 X 50', '#2 X 25', '#2 X 150', '#2 X 50', '#2 X 75', '#3 X 25', '#3 X 50']
      }
    ],
    specs: { length: '25mm-150mm', diameter: 'PH1-PH3 / PZ1-PZ3', threadType: 'N/A' }
  },
  {
    id: 'bit-3',
    name: 'Square Drive Bits – 1/4" Drive',
    description: 'Precision square drive bits optimized for specialized board and wood screws.',
    category: 'bits-sockets',
    material: 'Hardened Steel',
    finish: 'Black Oxide',
    headStyle: 'Square',
    driveType: '1/4" Hex Shank',
    price: 0.95,
    image: 'https://i.ibb.co/gF67MkDP/SQUARE-DRIVE-BITS.jpg',
    stockStatus: 'In Stock',
    sizes: [
      '#0 X 25 (For #4)', 
      '#0 X 50 (For #4)', 
      '#1 X 25 (For #6)', 
      '#1 X 30 (For #6)', 
      '#1 X 50 (For #6)', 
      '#2 X 25 (For #8)', 
      '#2 X 50 (For #8)', 
      '#3 X 25 (For #10)', 
      '#3 X 50 (For #10)'
    ],
    specs: { length: '25mm-50mm', diameter: '#0-#3', threadType: 'N/A' }
  },
  {
    id: 'anchor-1',
    name: '3 Piece Expansion Anchors Assembled Z-Yellow',
    description: 'Heavy-duty 3-piece expansion anchor for concrete and masonry fastening.',
    category: 'anchors',
    material: 'Steel',
    finish: 'Zinc Yellow',
    headStyle: 'Hex',
    driveType: 'External Hex',
    price: 1.25,
    image: 'https://i.ibb.co/C5cRQQsf/3-PIECE-EXPANSION-ANCHORS-ASSEMBLED-Z-YELLOW.jpg',
    stockStatus: 'In Stock',
    sizes: ['5 X 50', '6 X 65', '8 X 65', '10 X 75', '12 X 85', '16 X 135', '20 X 140'],
    specs: { length: 'Multiple', diameter: 'Multiple', threadType: 'Expansion' }
  },
  {
    id: 'anchor-2',
    name: 'Drop In Anchors - Zinc Plated',
    description: 'Internally threaded drop-in anchor for flush mounting in concrete.',
    category: 'anchors',
    material: 'Steel',
    finish: 'Zinc Plated',
    headStyle: 'Flat (Internal)',
    driveType: 'Metric Thread',
    price: 0.95,
    image: 'https://i.ibb.co/XfqQSZ6T/DROP-IN-ANCHORS-ZINC-PLATED.jpg',
    stockStatus: 'In Stock',
    sizes: ['M6', 'M8', 'M10', 'M12', 'M16', 'M20'],
    specs: { length: 'Flush', diameter: 'M6-M20', threadType: 'Metric' }
  },
  {
    id: 'anchor-3',
    name: 'Nail-In Anchors With Nylon Plug',
    description: 'Nylon nail-in anchor for rapid, light-duty fastening into solid substrates.',
    category: 'anchors',
    material: 'Nylon / Steel',
    finish: 'Zinc Plated / Natural',
    headStyle: 'Pan Head',
    driveType: 'Nail / Screw',
    price: 0.12,
    image: 'https://i.ibb.co/MxYBhryC/NAIL-IN-ANCHORS-WITH-NYLON-PLUG.jpg',
    stockStatus: 'In Stock',
    sizes: ['5 X 35', '5 X 40', '5 X 50', '6 X 35', '6 X 40', '6 X 45', '6 X 50', '6 X 55', '6 X 60', '6 X 70', '6 X 80', '8 X 60', '8 X 80', '8 X 100', '8 X 120', '8 X 135'],
    specs: { length: 'Multiple', diameter: '5mm-8mm', threadType: 'Nail-In' }
  },
  {
    id: 'anchor-4',
    name: 'Sleeve Anchors - Zinc Yellow',
    description: 'High-strength sleeve anchor with hex nut and washer for structural fixing.',
    category: 'anchors',
    material: 'Steel',
    finish: 'Zinc Yellow',
    headStyle: 'Hex Nut',
    driveType: 'External Hex',
    price: 0.85,
    image: 'https://i.ibb.co/9m6zR4tW/SLEEVE-ANCHORS-ZINC-YELLOW.jpg',
    stockStatus: 'In Stock',
    sizes: ['6 X 40', '6 X 60', '8 X 40', '8 X 65', '8 X 85', '10 X 50', '10 X 77', '10 X 97', '12 X 60', '12 X 75', '12 X 100', '16 X 50', '16 X 65', '16 X 111', '16 X 147', '20 X 105', '20 X 130', '20 X 160'],
    specs: { length: 'Multiple', diameter: '6mm-20mm', threadType: 'Expansion Sleeve' }
  },
  {
    id: 'anchor-5',
    name: 'Wedge Anchors - Zinc Yellow',
    description: 'Expansion wedge anchor for heavy-duty anchoring into solid concrete.',
    category: 'anchors',
    material: 'Steel',
    finish: 'Zinc Yellow',
    headStyle: 'Hex Nut',
    driveType: 'Metric Thread',
    price: 1.45,
    image: 'https://i.ibb.co/pByfWQM1/WEDGE-ANCHORS-ZINC-YELLOW.jpg',
    stockStatus: 'In Stock',
    sizes: ['8 X 100', '10 X 75', '10 X 90', '12 X 80', '12 X 110', '16 X 90', '16 X 110', '16 X 130', '20 X 110', '20 X 130', '20 X 160'],
    specs: { length: 'Multiple', diameter: '8mm-20mm', threadType: 'Metric' }
  },
  {
    id: 'p1',
    name: 'Csk Pozi Chipboard Screw Z/P',
    description: 'Universal countersunk screw with Pozi drive, Zinc plated for general interior use.',
    category: 'screws',
    material: 'Steel',
    finish: 'Zinc Plated (Z/P)',
    headStyle: 'Countersunk',
    driveType: 'Pozi',
    price: 0.15,
    image: 'https://picsum.photos/seed/p1/400/400',
    stockStatus: 'In Stock',
    specs: { length: '40mm', diameter: '4.0mm', threadType: 'Full Thread' }
  },
  {
    id: 'p3',
    name: 'Hex Washer Head Roofing Screw',
    description: 'Self-drilling roofing screw with bonded EPDM washer.',
    category: 'roofing-screws',
    material: 'Steel',
    finish: 'Climaseal',
    headStyle: 'Hex Washer',
    driveType: 'Hex',
    price: 0.45,
    image: 'https://picsum.photos/seed/p3/400/400',
    stockStatus: 'In Stock',
    specs: { length: '65mm', diameter: '5.5mm', threadType: 'Self-Drilling' }
  },
  {
    id: 'p4',
    name: 'Stainless A4 Socket Cap Screw',
    description: 'Marine-grade stainless steel socket head fastener.',
    category: 'socket-head-fasteners',
    material: 'Stainless Steel (A4)',
    finish: 'Natural',
    headStyle: 'Socket Cap',
    driveType: 'Hex Socket',
    price: 2.85,
    image: 'https://picsum.photos/seed/socket1/400/400',
    stockStatus: 'In Stock',
    specs: { length: '30mm', diameter: 'M8', threadType: 'Metric' }
  },
  {
    id: 'p5',
    name: 'Nylon Expansion Wall Plug',
    description: 'Professional grade nylon plug for secure masonry fixing.',
    category: 'wall-plugs',
    material: 'Nylon',
    finish: 'Natural',
    headStyle: 'Flanged',
    driveType: 'N/A',
    price: 0.08,
    image: 'https://picsum.photos/seed/plug1/400/400',
    stockStatus: 'In Stock',
    specs: { length: '40mm', diameter: '8mm', threadType: 'Universal' }
  }
];